"""empty message

Revision ID: 45c6e02a9f93
Revises: 67c2a8604cc5
Create Date: 2019-08-22 23:07:07.091820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c6e02a9f93'
down_revision = '67c2a8604cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lease_esignatures', sa.Column('status', sa.Enum('pending', 'processing', 'signed', 'executed', name='statusenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lease_esignatures', 'status')
    # ### end Alembic commands ###
