"""empty message

Revision ID: 4d304b4bb819
Revises: 0b1771fbe557
Create Date: 2019-08-23 21:53:01.021694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d304b4bb819'
down_revision = '0b1771fbe557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
